# Generated by Django 5.1.5 on 2025-06-09 10:19

import apps.reservas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=apps.reservas.models.gerar_numero_ingresso, max_length=12, unique=True, verbose_name='Número')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('desconto', models.BooleanField(default=False, verbose_name='Desconto Aplicado')),
                ('tipo_desconto', models.CharField(choices=[('estudante', 'Estudante'), ('idoso', 'Idoso'), ('promocional', 'Promocional'), ('nenhum', 'Nenhum')], default='nenhum', max_length=20, verbose_name='Tipo de Desconto')),
                ('assentos', models.TextField(help_text='Assentos reservados (formato JSON)', verbose_name='Assentos')),
                ('status', models.CharField(choices=[('emitido', 'Emitido'), ('utilizado', 'Utilizado'), ('cancelado', 'Cancelado')], default='emitido', max_length=50, verbose_name='Status')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'db_table': 'ingressos',
                'ordering': ['reserva', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Reserva')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=50, verbose_name='Status')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sessoes.sessao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-data_hora_reserva'],
            },
        ),
    ]
