# Generated by Django 5.1.5 on 2025-06-09 10:19

import apps.filmes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('duracao_minutos', models.IntegerField(verbose_name='Duração (minutos)')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('classificacao', models.CharField(max_length=100, verbose_name='Classificação')),
                ('site_oficial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Oficial')),
                ('trailer_oficial_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trailer Oficial')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=apps.filmes.models.filme_poster_path, verbose_name='Poster')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'db_table': 'filmes',
                'ordering': ['-data_lancamento', 'titulo'],
            },
        ),
    ]
