# Generated by Django 5.1.5 on 2025-06-09 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Base')),
                ('tipo', models.CharField(choices=[('2d', '2D'), ('3d', '3D'), ('imax', 'IMAX')], default='2d', max_length=10, verbose_name='Tipo de Sessão')),
                ('idioma', models.CharField(choices=[('legendado', 'Legendado'), ('dublado', 'Dublado')], default='legendado', max_length=10, verbose_name='Idioma da Sessão')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='filmes.filme', verbose_name='Filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='cinemas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'db_table': 'sessoes',
                'ordering': ['horario'],
            },
        ),
    ]
