# Generated by Django 5.1.5 on 2025-06-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'db_table': 'cinemas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='cinemas.cinema', verbose_name='Cinema')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'salas',
                'ordering': ['cinema', 'nome'],
            },
        ),
    ]
